FORMAT: 1A

# Mobile News API
Mobile News API is a **text and image news service** for mobile devices

## Authentication
(will be specified later; will probably rely on authorization tokens)

## Media Types
Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# Mobile News API Root [/]
Gist Fox API entry point.

This resource does not have any attributes. Instead it offers the initial API affordances in the form of the HTTP Link header and 
HAL links.

## Article [/articles/{id}]
A single Article object. The Article resource is the central resource in our mobile news service. 

The Article resource has the following attributes: 

- id
- title
- summary
- content
- created_at
- published_at
- category

The states *id* and *created_at* are assigned at the moment of creation. 

+ Parameters
    + id (string) ... ID of the Article in the form of a GUID

+ Model (application/hal+json)

    HAL+JSON representation of Article Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.

    + Body

            {
                "_links": {
                    "self": { "href": "/articles/42" },
                    "publish": { "href": "/publishing/articles/42" },
                    "attach-image": {"href": "/articles/42/images?[image-id]}
                },
                "id": "42",
                "title": "My article's title",
                "summary": "My article's summary",
                "content": "Lots of text for my content",
                "created_at": "2014-04-14T02:15:15Z",
                "published_at": "2014-04-15T12:15:15Z",
                "category": "Finances"
            }

### Retrieve a Single Article [GET]
+ Response 200
    
    [Article][]

### Post a new Article [POST]
To create a new article, simply send the whole article

+ Request (application/json)

    [Article][]
    
+ Response 201

        {
            "_links": {
                    "self": { "href": "/articles/42" },
                    "publish": { "href": "/publishing/articles/42" },
                    "attach-image": {"href": "/articles/42/images?[image-id]}
                },
                "id": "42"
        }

### Edit a Article [PUT]
To update an Article send the whole article with some values changed.

+ Request (application/json)
    
    [Article][]

+ Response 200
    
### Delete an Article [DELETE]
+ Response 204

## Publishing [/publishing/articles/{id}]

Marks an article as ready to be served to client news readers

+ Parameters
    + id (string) ... ID of the Article in the form of a GUID

+ Model (application/hal+json)

    Model used by the Publishing operation.

    + Body

            {
                "_links": {
                    "self": { "href": "/publishing/articles/42" },
                    "unpublish": { "href": "/publishing/articles/42/removal" },
                    "view": { "href": "/published/articles/42" }
                },
                "location": "/published/articles/42"
            }


### Publish an article [POST]
+ Response 202
    
    [Publishing][]

## Image [/articles/42/images{?image_type}]

An article may have several images; the image-type specifies what the image is intended for (cover, top of the article)

+ Parameters
    + image_type (string) ... the image-type specifies what the image is intended for (cover, top of the article)
    
### Upload an image [POST]

+ Response 202

### View image related to an article [GET]

+ Response 200



